-- al-yo-bo initial schema. See docs/MODEL.md for the authoritative description.
-- UUIDv7 primary keys are generated by the application (packages/db) and stored as
-- 16-byte BLOBs; bun:sqlite exposes no user-defined SQL functions, so columns carry
-- no DEFAULT and the CHECK constraints enforce the BLOB shape instead.

CREATE TABLE categories (
  id          BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  name        TEXT NOT NULL,
  description TEXT,
  created_at  INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE UNIQUE INDEX categories_name_unique ON categories(name);

CREATE TABLE bookmarks (
  id           BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  url          TEXT NOT NULL,
  title        TEXT,
  description  TEXT,
  content      TEXT,
  metadata     TEXT,
  category_id  BLOB REFERENCES categories(id) ON DELETE SET NULL
                    CHECK (category_id IS NULL OR (typeof(category_id) = 'blob' AND length(category_id) = 16)),
  content_hash TEXT,
  scraped_at   INTEGER,
  created_at   INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at   INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE UNIQUE INDEX bookmarks_url_unique ON bookmarks(url);
CREATE INDEX bookmarks_category ON bookmarks(category_id);

CREATE TABLE tags (
  id          BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  category_id BLOB REFERENCES categories(id) ON DELETE SET NULL
                   CHECK (category_id IS NULL OR (typeof(category_id) = 'blob' AND length(category_id) = 16)),
  name        TEXT NOT NULL,
  description TEXT,
  status      TEXT NOT NULL CHECK (status IN ('active', 'proposed', 'deprecated')),
  created_at  INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE UNIQUE INDEX tags_scoped_name_unique ON tags(category_id, name) WHERE category_id IS NOT NULL;
CREATE UNIQUE INDEX tags_global_name_unique ON tags(name)                   WHERE category_id IS NULL;
CREATE INDEX tags_category ON tags(category_id);

CREATE TABLE classification_runs (
  id                 BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  bookmark_id        BLOB NOT NULL REFERENCES bookmarks(id) ON DELETE CASCADE
                          CHECK (typeof(bookmark_id) = 'blob' AND length(bookmark_id) = 16),
  classifier         TEXT NOT NULL,
  classifier_version TEXT,
  model              TEXT,
  confidence         REAL,
  created_at         INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE INDEX classification_runs_bookmark ON classification_runs(bookmark_id, created_at);

CREATE TABLE classification_results (
  id          BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  run_id      BLOB NOT NULL REFERENCES classification_runs(id) ON DELETE CASCADE
                   CHECK (typeof(run_id) = 'blob' AND length(run_id) = 16),
  tag_id      BLOB NOT NULL REFERENCES tags(id) ON DELETE CASCADE
                   CHECK (typeof(tag_id) = 'blob' AND length(tag_id) = 16),
  probability REAL NOT NULL,
  rank        INTEGER,
  selected    INTEGER NOT NULL DEFAULT 0,
  raw_label   TEXT,
  UNIQUE (run_id, tag_id)
) STRICT;

CREATE INDEX classification_results_tag ON classification_results(tag_id);

CREATE TABLE bookmark_tags (
  id          BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  bookmark_id BLOB NOT NULL REFERENCES bookmarks(id) ON DELETE CASCADE
                   CHECK (typeof(bookmark_id) = 'blob' AND length(bookmark_id) = 16),
  tag_id      BLOB NOT NULL REFERENCES tags(id) ON DELETE CASCADE
                   CHECK (typeof(tag_id) = 'blob' AND length(tag_id) = 16),
  source      TEXT NOT NULL CHECK (source IN ('classifier', 'user', 'import')),
  confidence  REAL,
  run_id      BLOB REFERENCES classification_runs(id) ON DELETE SET NULL
                   CHECK (run_id IS NULL OR (typeof(run_id) = 'blob' AND length(run_id) = 16)),
  created_at  INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at  INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (bookmark_id, tag_id)
) STRICT;

CREATE INDEX bookmark_tags_tag ON bookmark_tags(tag_id);

CREATE VIRTUAL TABLE bookmark_fts USING fts5(
  bookmark_id UNINDEXED,
  url,
  title,
  description,
  content,
  tokenize = 'unicode61'
);

CREATE TABLE bookmark_embeddings (
  bookmark_id BLOB PRIMARY KEY NOT NULL CHECK (typeof(bookmark_id) = 'blob' AND length(bookmark_id) = 16)
                   REFERENCES bookmarks(id) ON DELETE CASCADE,
  model       TEXT NOT NULL,
  dims        INTEGER NOT NULL,
  embedding   BLOB NOT NULL,
  updated_at  INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

-- Server-set timestamps: force created_at/updated_at on insert and bump updated_at
-- on every update, overriding any client-sent value.
CREATE TRIGGER categories_force_created AFTER INSERT ON categories BEGIN
  UPDATE categories SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER bookmarks_force_created AFTER INSERT ON bookmarks BEGIN
  UPDATE bookmarks
     SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER),
         updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER)
   WHERE id = NEW.id;
END;

CREATE TRIGGER bookmarks_bump_updated AFTER UPDATE ON bookmarks BEGIN
  UPDATE bookmarks SET updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER tags_force_created AFTER INSERT ON tags BEGIN
  UPDATE tags SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER classification_runs_force_created AFTER INSERT ON classification_runs BEGIN
  UPDATE classification_runs SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER bookmark_tags_force_created AFTER INSERT ON bookmark_tags BEGIN
  UPDATE bookmark_tags
     SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER),
         updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER)
   WHERE id = NEW.id;
END;

CREATE TRIGGER bookmark_tags_bump_updated AFTER UPDATE ON bookmark_tags BEGIN
  UPDATE bookmark_tags SET updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER bookmark_embeddings_force_created AFTER INSERT ON bookmark_embeddings BEGIN
  UPDATE bookmark_embeddings SET updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE bookmark_id = NEW.bookmark_id;
END;

-- Full-text index kept in sync from the bookmarks table (virtual tables cannot be
-- foreign-key targets, so sync is trigger-driven).
CREATE TRIGGER bookmarks_fts_insert AFTER INSERT ON bookmarks BEGIN
  INSERT INTO bookmark_fts (bookmark_id, url, title, description, content)
  VALUES (NEW.id, NEW.url, NEW.title, NEW.description, NEW.content);
END;

CREATE TRIGGER bookmarks_fts_update AFTER UPDATE ON bookmarks BEGIN
  DELETE FROM bookmark_fts WHERE bookmark_id = OLD.id;
  INSERT INTO bookmark_fts (bookmark_id, url, title, description, content)
  VALUES (NEW.id, NEW.url, NEW.title, NEW.description, NEW.content);
END;

CREATE TRIGGER bookmarks_fts_delete AFTER DELETE ON bookmarks BEGIN
  DELETE FROM bookmark_fts WHERE bookmark_id = OLD.id;
END;
