-- al-yo-bo v2 initial schema — the database is born here in its final shape
-- (docs/MODEL.md §Tables). No datasets, no sections: one workspace, a tree of
-- categories, globally-unique URLs and tag names. UUIDv7 primary keys are
-- generated by the application (packages/db) and stored as 16-byte BLOBs;
-- bun:sqlite exposes no user-defined SQL functions, so columns carry no DEFAULT
-- and the CHECK constraints enforce the BLOB shape instead.

CREATE TABLE profile (
  id                BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  name              TEXT,
  github_username   TEXT,
  avatar_path       TEXT,
  dev_profile       TEXT,                         -- JSON: wizard questionnaire
  setup_completed_at INTEGER,                     -- NULL = setup wizard pending
  created_at        INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at        INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

-- Fixed sentinel id (all-zero): the singleton profile row — the app reads the
-- profile by id, never by name, and there is no delete path (MODEL.md principle 8).
INSERT INTO profile (id) VALUES (X'00000000000000000000000000000000');

-- Orderable category tree (MODEL.md principle 2). Cycles are impossible to
-- express in SQL with a self-FK, so the app layer validates every parent
-- assignment (queries/categories.ts); sort_order is an app-generated
-- fractional-index string, lexicographically ordered under BINARY collation.
CREATE TABLE categories (
  id            BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  parent_id     BLOB REFERENCES categories(id) ON DELETE CASCADE
                    CHECK (parent_id IS NULL OR (typeof(parent_id) = 'blob' AND length(parent_id) = 16)),
  sort_order    TEXT NOT NULL,
  name          TEXT NOT NULL,
  description   TEXT,
  created_at    INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

-- Sibling names are unique; the NULL-parent case needs its own partial index
-- (a plain UNIQUE(parent_id, name) treats NULLs as distinct and never fires).
CREATE UNIQUE INDEX categories_root_name_unique ON categories(name) WHERE parent_id IS NULL;
CREATE UNIQUE INDEX categories_child_name_unique ON categories(parent_id, name) WHERE parent_id IS NOT NULL;
CREATE INDEX categories_parent_order ON categories(parent_id, sort_order);

CREATE TABLE bookmarks (
  id           BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  url          TEXT NOT NULL,
  title        TEXT,
  description  TEXT,
  content      TEXT,                              -- scraped page content as markdown
  metadata     TEXT,                              -- JSON: site name, author, favicon, og:*, image, scrape, import
  category_id  BLOB REFERENCES categories(id) ON DELETE SET NULL
                   CHECK (category_id IS NULL OR (typeof(category_id) = 'blob' AND length(category_id) = 16)),
  content_hash TEXT,                              -- hash of scraped content, for change detection
  scraped_at   INTEGER,
  status       TEXT NOT NULL DEFAULT 'active'     -- effective scrape lifecycle (MODEL.md)
                   CHECK (status IN ('active', 'invalid')),
  scrape_attempts INTEGER NOT NULL DEFAULT 0,     -- consecutive dead-link failures (reset on success)
  created_at   INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at   INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

-- URL uniqueness is global — one workspace means one row per URL.
CREATE UNIQUE INDEX bookmarks_url_unique ON bookmarks(url);
CREATE INDEX bookmarks_category ON bookmarks(category_id);

-- Controlled vocabulary: one flat global namespace (tags have no category —
-- MODEL.md principle 2; the classifier candidate set is all active tags).
CREATE TABLE tags (
  id            BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  name          TEXT NOT NULL,
  description   TEXT,
  status        TEXT NOT NULL CHECK (status IN ('active', 'deprecated')),
  created_at    INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE UNIQUE INDEX tags_name_unique ON tags(name);

-- Classification provenance anchor. A run records that the classifier was
-- consulted for a bookmark; the effective assignments it produced live in
-- bookmark_tags (source = 'classifier', run_id set). No per-result or unknown-
-- label tables: the background classifier never creates vocabulary, and only
-- user-confirmed actions change the effective assignment set (MODEL.md).
CREATE TABLE classification_runs (
  id                 BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  bookmark_id        BLOB NOT NULL REFERENCES bookmarks(id) ON DELETE CASCADE
                          CHECK (typeof(bookmark_id) = 'blob' AND length(bookmark_id) = 16),
  classifier         TEXT NOT NULL,               -- e.g. "ollaya"
  classifier_version TEXT,                        -- runtime version
  model              TEXT,                        -- decision model id, e.g. "laya"
  confidence         REAL,                        -- run-level confidence, optional
  created_at         INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE INDEX classification_runs_bookmark ON classification_runs(bookmark_id, created_at);

-- The effective assignment shown in the UI (MODEL.md principle 4: separate
-- evidence from effective state). User/import rows are never overwritten by
-- the classifier (queries/bookmark-tags.ts).
CREATE TABLE bookmark_tags (
  id          BLOB PRIMARY KEY NOT NULL CHECK (typeof(id) = 'blob' AND length(id) = 16),
  bookmark_id BLOB NOT NULL REFERENCES bookmarks(id) ON DELETE CASCADE
                   CHECK (typeof(bookmark_id) = 'blob' AND length(bookmark_id) = 16),
  tag_id      BLOB NOT NULL REFERENCES tags(id) ON DELETE CASCADE
                   CHECK (typeof(tag_id) = 'blob' AND length(tag_id) = 16),
  source      TEXT NOT NULL CHECK (source IN ('classifier', 'user', 'import')),
  confidence  REAL,
  run_id      BLOB REFERENCES classification_runs(id) ON DELETE SET NULL  -- evidence, if classifier-sourced
                   CHECK (run_id IS NULL OR (typeof(run_id) = 'blob' AND length(run_id) = 16)),
  created_at  INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at  INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (bookmark_id, tag_id)
) STRICT;

CREATE INDEX bookmark_tags_tag ON bookmark_tags(tag_id);

-- Durable copy of the vector data (one row per embedded bookmark); the Qdrant
-- collection is a rebuildable serving copy repaired from this table (MODEL.md
-- principle 7). `model` stores the configured EMBEDDING_MODEL, never the
-- provider echo (ARCHITECTURE §8 — test-pinned rule).
CREATE TABLE bookmark_embeddings (
  bookmark_id BLOB PRIMARY KEY NOT NULL CHECK (typeof(bookmark_id) = 'blob' AND length(bookmark_id) = 16)
                   REFERENCES bookmarks(id) ON DELETE CASCADE,
  model       TEXT NOT NULL,                        -- configured EMBEDDING_MODEL (not the provider echo)
  dims        INTEGER NOT NULL,                     -- must equal dimension(model)
  embedding   BLOB NOT NULL,                        -- little-endian Float32 array, length = dims * 4 bytes
  updated_at  INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

-- Keyword index (internal structure — FTS5 virtual tables are not STRICT and
-- have no UUID primary key; MODEL.md §Search structures). bookmark_id stores
-- the BLOB UUID so bookmarks.id = bookmark_fts.bookmark_id joins directly.
CREATE VIRTUAL TABLE bookmark_fts USING fts5(
  bookmark_id UNINDEXED,
  url,
  title,
  description,
  content,
  tokenize = 'unicode61'
);

-- Server-set timestamps: force created_at/updated_at on insert and bump
-- updated_at on every update, overriding any client-sent value (MODEL.md).
CREATE TRIGGER profile_force_created AFTER INSERT ON profile BEGIN
  UPDATE profile
     SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER),
         updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER)
   WHERE id = NEW.id;
END;

CREATE TRIGGER profile_bump_updated AFTER UPDATE ON profile BEGIN
  UPDATE profile SET updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER categories_force_created AFTER INSERT ON categories BEGIN
  UPDATE categories SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER bookmarks_force_created AFTER INSERT ON bookmarks BEGIN
  UPDATE bookmarks
     SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER),
         updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER)
   WHERE id = NEW.id;
END;

CREATE TRIGGER bookmarks_bump_updated AFTER UPDATE ON bookmarks BEGIN
  UPDATE bookmarks SET updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER tags_force_created AFTER INSERT ON tags BEGIN
  UPDATE tags SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER classification_runs_force_created AFTER INSERT ON classification_runs BEGIN
  UPDATE classification_runs SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER bookmark_tags_force_created AFTER INSERT ON bookmark_tags BEGIN
  UPDATE bookmark_tags
     SET created_at = CAST(unixepoch('subsec') * 1000 AS INTEGER),
         updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER)
   WHERE id = NEW.id;
END;

CREATE TRIGGER bookmark_tags_bump_updated AFTER UPDATE ON bookmark_tags BEGIN
  UPDATE bookmark_tags SET updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE id = NEW.id;
END;

CREATE TRIGGER bookmark_embeddings_force_created AFTER INSERT ON bookmark_embeddings BEGIN
  UPDATE bookmark_embeddings SET updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE bookmark_id = NEW.bookmark_id;
END;

-- Full-text index kept in sync from the bookmarks table (virtual tables cannot
-- be foreign-key targets, so sync is trigger-driven).
CREATE TRIGGER bookmarks_fts_insert AFTER INSERT ON bookmarks BEGIN
  INSERT INTO bookmark_fts (bookmark_id, url, title, description, content)
  VALUES (NEW.id, NEW.url, NEW.title, NEW.description, NEW.content);
END;

CREATE TRIGGER bookmarks_fts_update AFTER UPDATE ON bookmarks BEGIN
  DELETE FROM bookmark_fts WHERE bookmark_id = OLD.id;
  INSERT INTO bookmark_fts (bookmark_id, url, title, description, content)
  VALUES (NEW.id, NEW.url, NEW.title, NEW.description, NEW.content);
END;

CREATE TRIGGER bookmarks_fts_delete AFTER DELETE ON bookmarks BEGIN
  DELETE FROM bookmark_fts WHERE bookmark_id = OLD.id;
END;
